### PR TITLE
added seek in live games, start live from beginning options

### PR DESCRIPTION
**Pull request by tonywagner**
- Changed default live stream from "slide" to "complete" so it's now possible to seek/pause within live streams.
- Added variable to track spoiler status for individual games, from create_game_listitem to play_stream (False means no spoiler)
- If "no spoiler" is set for a requested live game, it will start playing from the beginning using the broadcast start time (unless "Catch Up" is enabled, then the user can choose between "Catch Up", "Beginning", or "Live" for all live games).
- Hide "Highlights" option, and Catch Up/Beginning/Live dialog, if a Kodi resume point has been selected

Question: the "Catch Up" option doesn't work for me, although I've never used it before either. Is it just supposed to show highlights in order? If it's not functional anymore, maybe the setting could be re-named -- an "Always Ask" for starting live games either Beginning or Live?

### CODE REVIEW

**Comment by eracknaphobia** [comment]
> Question: the "Catch Up" option doesn't work for me, although I've never used it before either. Is it just supposed to show highlights in order? If it's not functional anymore, maybe the setting could be re-named -- an "Always Ask" for starting live games either Beginning or Live?

It once worked 😉 but I can't say I've used it in a very long time. It used to play highlights in order then jump to the live stream. It could probably be removed if a play from beginning option is now available.

**Comment by tonywagner** [comment]
> It once worked 😉 but I can't say I've used it in a very long time. It used to play highlights in order then jump to the live stream. It could probably be removed if a play from beginning option is now available.

Actually I think I can get "Catch Up" working again pretty easily? I'll try it tonight when games are live and report back.

**Comment by tonywagner** [comment]
That was easy, just a slight JSON change got "Catch Up" working again.

Let me know if you need me to do anything to help push these changes into the Matrix version and Kodi repo.

**Comment by eracknaphobia** [comment]
Thanks! Will test it out.

**Pull request merged**
