### PR TITLE
List favorite team's game(s) first

### PR DESCRIPTION
**Pull request by thromer**

### CODE REVIEW

**Comment by tonywagner** [comment]
This one may not be necessary, as my latest pull request includes an "autoplay favorite team when live" option, as requested: https://github.com/eracknaphobia/plugin.video.mlbtv/pull/44

**Comment by thromer** [comment]
> This one may not be necessary, as my latest pull request includes an "autoplay favorite team when live" option, as requested: #44

I think #43 would still be useful on its own, since autoplay doesn't always apply.

**Comment by tonywagner** [comment]
That makes sense. Since my PR also modified the create_game_listitem function, I just rolled your changes into my PR, if you want to update and test.

**Comment by thromer** [comment]
Thanks! My laptop just went belly-up so I won't be able to test it unfortunately.

**Comment by eracknaphobia** [comment]
@thromer @tonywagner Thanks for the updates!
So we are closing this PR and pulling #44, correct?

**Comment by tonywagner** [comment]
> So we are closing this PR and pulling #44, correct?

Yes, https://github.com/eracknaphobia/plugin.video.mlbtv/pull/44 now incorporates the changes from this PR too

**Pull request closed without merging**
